# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to my own server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: "Deploy to Staging" 
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./_site/
          remote_path: /root/www/
          remote_host: ${{ secrets.DC_HOST }}
          remote_port: ${{ secrets.DC_PORT }}
          remote_user: ${{ secrets.DC_USER }}
          remote_key: ${{ secrets.DC_PASS }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          username: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_PASS }}
          debug: false
          script: "cp /root/www/Caddyfile /root/caddy/; cd /root/; docker-compose up -d caddy; cd /root/code/cavemancave.github.io; git fetch --recurse-submodules; git reset origin/main --hard --recurse-submodules;"
