name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      
      - name: "Deploy to my server" 
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./public/
          remote_path: /root/www/
          remote_host: ${{ secrets.DC_HOST }}
          remote_port: ${{ secrets.DC_PORT }}
          remote_user: ${{ secrets.DC_USER }}
          remote_key: ${{ secrets.DC_PASS }}
  
      - name: "Trigger reload"
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DC_HOST }}
          port: ${{ secrets.DC_PORT }}
          username: ${{ secrets.DC_USER }}
          key: ${{ secrets.DC_PASS }}
          debug: false
          script: "docker exec -w /etc/caddy caddy caddy reload"