# Build and upload release When tag v*.*.*
name: Release Build

on:
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
        
      - name: Zip site
        run: |
          zip -r site.zip _site
          
      - name: Use last commit message as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(git log -1 --pretty=%B | cat)                 # <--- Get last commit message
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"         # <--- Set environment variable
          
      - name: Upload build result to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: site.zip
          asset_name: site_$tag.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }} 
